Flash booted state
luxonis/XLink pull request #7
Opened 2021-05-21 00:28 UTC by themarpe

2021-07-21 22:56 UTC, szabi-luxonis requested changes

2021-07-21 22:56 UTC, szabi-luxonis commented on src/shared/XLinkDevice.c
> +        case X_LINK_USB_VSC: return "X_LINK_USB_VSC";
add XLINK_TCP_IP

2021-07-22 15:31 UTC, alex-luxonis approved these changes
Later on I think we should change a bit to allow passing custom VID/PID that were eventually set through pre-boot config?

2021-07-22 16:20 UTC, themarpe commented
@alex-luxonis yes - in the works in branch `device_search_improvements` :) 
Right now it took a too wide turn with refactoring - removed all Windows specific stuff and tried going with libusb only, but libusb doesn't have nice integration options available (no CMake, only VS solutions for Windows), so will rather keep Windows WinUSB and libusb for UNIX.

2021-07-24 20:46 UTC, merged