Clang Support
luxonis/XLink pull request #84
Opened 2024-07-15 02:34 UTC by onthegrid007

Adds Clang support
Fixes issues:
https://github.com/luxonis/XLink/issues/80
https://github.com/luxonis/depthai-core/issues/1044

2024-07-15 16:15 UTC, themarpe requested changes

2024-07-15 16:15 UTC, themarpe commented on CMakeLists.txt
>          if(WIN32 AND NOT MINGW)
```suggestion
        if(WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
```

2024-07-15 16:15 UTC, themarpe commented on CMakeLists.txt
>          if(WIN32 AND NOT MINGW)
Probably above is the way to go then, as it seems that DELAYLOAD is MSVC feature (and not "everyone's but Clang's feature)
Also, the delayimp.lib then isn't required.

2024-07-19 02:43 UTC, onthegrid007 commented
Could this get pushed downstream so depthai-core can use it properly?

2024-07-19 12:24 UTC, themarpe requested changes

2024-07-19 12:24 UTC, themarpe commented on CMakeLists.txt
> +			endif()
Seems to be too indented & with tabs instead of space?

2024-07-19 12:24 UTC, themarpe commented on CMakeLists.txt
> +			endif()
Also, this if&endif statement can be removed, given that above if only allows msvc

2024-07-20 04:32 UTC, onthegrid007 commented
Done.

2024-07-22 10:36 UTC, themarpe requested changes
@onthegrid007 sorry, one additional thing - do you mind adding it to CI as well?

2024-07-22 10:36 UTC, themarpe commented
(otherwise LGTM)

2024-07-22 18:41 UTC, onthegrid007 commented
I can if you could tell me what the CI is...?

2024-07-22 18:58 UTC, themarpe commented
@onthegrid007 the Continious Integration - there is a .yml workflow file that runs "tests/builds" of the codebase using various platforms/operating systems. `windows-latest` currently only does MSVC, so we should add also Clang there

2024-07-22 19:03 UTC, onthegrid007 commented
Yes I can try. Give ma little bit

2024-07-24 01:36 UTC, onthegrid007 commented
Done.

2024-07-24 11:24 UTC, onthegrid007 commented
It succeeded...

2024-07-24 23:04 UTC, themarpe commented
I mean that clang wasn't used to compile, but it was still MSVC: 

> -- The CXX compiler identification is MSVC 19.40.33812.0

Under the windows, clang build

2024-07-27 06:21 UTC, onthegrid007 commented
I'll make a change and see if it fixes it

2024-07-30 00:26 UTC, onthegrid007 commented
Ninja or some other makefile system is required for cmake to execute using clang properly, that has been added and should allow the CI to propagate...

2024-07-31 10:19 UTC, themarpe approved these changes
CC: @moratom please integrate, thanks

2024-07-31 11:21 UTC, merged